---
- name: Install apt packages 
  become: true
  apt:
    name:
      # essential build tools (gcc, make, etc)
      - build-essential
      - libtool
      - python
      - python3
      - pkg-config
      - rsync

      # Touchpad
      - libgtest-dev
      - libjsoncpp-dev

      # Needed for mounting recovery image
      - kpartx

      # for building kernel
      - git
      - fakeroot
      - build-essential
      - ncurses-dev
      - xz-utils
      - libssl-dev
      - bc
      - flex
      - libelf-dev
      - bison

      # Audio / CRAS dependencies
      - acpid
      - libudev-dev
      - libsbc-dev
      - libalsaplayer-dev
      - libiniparser-dev
      - ladspa-sdk
      - libspeex-dev
      - libspeexdsp-dev
      - libasound2-dev
    state: latest 

